In [1]:
from pathlib import Path
import pandas as pd

In [2]:
data = Path('Resource/Diabetes_Prediction_2018_2022.csv')
df = pd.read_csv(data)
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoke,Stroke,HeartDiseaseorAttack,PhysicalActivity,Fruits,...,AlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education
0,0,0,1,0,40,1,0,0,0,0,...,0,1,0,5,18,15,1,0,9,4
1,0,0,0,0,25,1,0,0,1,0,...,0,0,1,3,0,0,0,0,7,6
2,0,1,1,1,28,0,0,0,0,1,...,0,1,1,5,30,30,1,0,9,4
3,0,1,0,1,27,0,0,0,1,1,...,0,1,0,2,0,0,0,0,11,3
4,0,1,1,1,24,0,0,0,1,1,...,0,1,0,2,3,0,0,0,11,5

In [3]:
df["Diabetes_012"] = df["Diabetes_012"].replace(2,1)
df["Diabetes_012"].head()
df1 = df[(df["Diabetes_012"]==0)]
df2 = df[(df["Diabetes_012"]==1)]
#df["Diabetes_012"].value_counts()
df1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoke,Stroke,HeartDiseaseorAttack,PhysicalActivity,Fruits,...,AlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education
0,0,0,1,0,40,1,0,0,0,0,...,0,1,0,5,18,15,1,0,9,4
1,0,0,0,0,25,1,0,0,1,0,...,0,0,1,3,0,0,0,0,7,6
2,0,1,1,1,28,0,0,0,0,1,...,0,1,1,5,30,30,1,0,9,4
3,0,1,0,1,27,0,0,0,1,1,...,0,1,0,2,0,0,0,0,11,3
4,0,1,1,1,24,0,0,0,1,1,...,0,1,0,2,3,0,0,0,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249988,0,1,1,1,30,1,0,0,1,1,...,0,1,0,2,10,5,0,0,10,6
249990,0,1,1,1,25,1,0,0,1,1,...,0,1,0,3,0,0,0,1,8,6
249992,0,0,0,1,20,0,0,0,1,1,...,0,0,1,4,0,4,1,0,1,4
249993,0,0,1,1,25,0,0,0,1,1,...,0,1,0,3,0,0,0,0,9,4
249997,0,1,1,1,33,1,0,0,1,1,...,0,1,1,2,3,0,0,1,6,3

In [4]:
df2["Diabetes_012"].value_counts()

Diabetes_012
1    39069
Name: count, dtype: int64

In [5]:
no_to_drop = len(df1["Diabetes_012"])-len(df2["Diabetes_012"])
df1 = df1.drop(df1.index[:no_to_drop])
df1.reset_index(inplace=True,drop=True)

In [6]:
df1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoke,Stroke,HeartDiseaseorAttack,PhysicalActivity,Fruits,...,AlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education
0,0,0,0,0,22,1,0,0,0,1,...,0,1,0,1,30,0,0,0,6,6
1,0,0,0,1,23,0,0,0,1,1,...,0,1,0,1,0,0,0,0,9,6
2,0,0,1,1,25,0,0,1,1,0,...,0,1,0,3,0,0,0,0,12,6
3,0,0,0,1,28,0,0,0,1,0,...,0,1,0,3,0,30,0,0,10,5
4,0,0,1,1,32,1,0,0,1,1,...,0,1,0,1,2,0,1,0,9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39064,0,1,1,1,30,1,0,0,1,1,...,0,1,0,2,10,5,0,0,10,6
39065,0,1,1,1,25,1,0,0,1,1,...,0,1,0,3,0,0,0,1,8,6
39066,0,0,0,1,20,0,0,0,1,1,...,0,0,1,4,0,4,1,0,1,4
39067,0,0,1,1,25,0,0,0,1,1,...,0,1,0,3,0,0,0,0,9,4
39068,0,1,1,1,33,1,0,0,1,1,...,0,1,1,2,3,0,0,1,6,3

In [7]:
df = pd.concat([df1,df2], axis=0, ignore_index= True)
df

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoke,Stroke,HeartDiseaseorAttack,PhysicalActivity,Fruits,...,AlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education
0,0,0,0,0,22,1,0,0,0,1,...,0,1,0,1,30,0,0,0,6,6
1,0,0,0,1,23,0,0,0,1,1,...,0,1,0,1,0,0,0,0,9,6
2,0,0,1,1,25,0,0,1,1,0,...,0,1,0,3,0,0,0,0,12,6
3,0,0,0,1,28,0,0,0,1,0,...,0,1,0,3,0,30,0,0,10,5
4,0,0,1,1,32,1,0,0,1,1,...,0,1,0,1,2,0,1,0,9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78133,1,1,1,1,28,0,0,0,1,1,...,0,1,1,3,0,30,0,0,7,3
78134,1,1,1,1,24,1,0,0,1,0,...,0,1,0,3,0,0,0,1,9,4
78135,1,1,1,1,28,1,0,0,1,1,...,0,1,1,5,14,14,1,0,8,4
78136,1,1,0,1,22,0,0,0,1,1,...,0,1,0,3,0,0,0,0,8,3
78137,1,1,0,1,36,1,0,0,0,1,...,0,1,0,2,0,0,0,1,4,4

In [8]:
from sklearn.preprocessing import StandardScaler
df_scaled = df.drop(columns=["Diabetes_012"])

diabete_scaled = StandardScaler().fit_transform(df_scaled)

In [9]:
df_scaled = pd.DataFrame(diabete_scaled)

In [10]:
y = df["Diabetes_012"]
X = df_scaled

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(58603, 20)

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=1000,
                                random_state=1)
classifier

LogisticRegression(max_iter=1000, random_state=1)

In [13]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=1)

In [14]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7464805556029555
Testing Data Score: 0.7516764781162016

In [15]:
predictions = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
results.head(100)

    Prediction  Actual
0            0       0
1            0       0
2            1       1
3            1       1
4            1       1
..         ...     ...
95           1       0
96           1       1
97           0       0
98           0       0
99           0       0

[100 rows x 2 columns]

In [16]:
results["Actual"].value_counts()

Actual
1    9768
0    9767
Name: count, dtype: int64

In [17]:
results["Prediction"].value_counts()

Prediction
1    10087
0     9448
Name: count, dtype: int64

In [18]:
from sklearn.metrics import accuracy_score
# Display the accuracy score for the test dataset.
accuracy_score(y_test, predictions)

0.7516764781162016